# Central Configuration Hub

# Automated generation of reports
[pytest]
addopts = --html=reports/html-results/test_report.html --self-contained-html


;[pytest]
;addopts = --alluredir=reports/allure-results


;testpaths = tests


;Custom Markers (prevents warnings when using @pytest.mark.smoke)
markers =
    smoke: vital system health check tests
;    regression: full suite testing
    slow: tests that take a long time